### ISSUE TITLE
bug in train stage on my own dataset

### ISSUE THREAD

**Issue by DarkLeaves** [chou141253/FGVC-HERBS#16]
`(tsea)  ikaro@ikaros ~\....\FGVC-HERBS-master python main.py --c ./configs/config.yaml

Reading Config.......[success][0.007 sceonds]
Setting Environment...
Building Dataloader....[dataset] class number: 2
[dataset] class number: 2
    Train Samples: 697 (batch: 88)
    Validation Samples: 175 (batch: 22)
....[success][0.004 sceonds]
Building Model....Building...
Traceback (most recent call last):
  File "C:\Users\ikaro\Desktop\FGVC-HERBS-master\main.py", line 325, in <module>
    main(args, tlogger)
  File "C:\Users\ikaro\Desktop\FGVC-HERBS-master\main.py", line 256, in main
    train_loader, val_loader, model, optimizer, schedule, scaler, amp_context, start_epoch = set_environment(args, tlogger)
  File "C:\Users\ikaro\Desktop\FGVC-HERBS-master\main.py", line 55, in set_environment
    model = MODEL_GETTER[args.model_name](
  File "C:\Users\ikaro\Desktop\FGVC-HERBS-master\models\builder.py", line 260, in build_swintransformer
    return pim_module.PluginMoodel(backbone = backbone,
  File "C:\Users\ikaro\Desktop\FGVC-HERBS-master\models\pim_module\pim_module.py", line 441, in __init__
    self.fpn_down = FPN(outs, fpn_size, proj_type, upsample_type)
  File "C:\Users\ikaro\Desktop\FGVC-HERBS-master\models\pim_module\pim_module.py", line 234, in __init__
    nn.Linear(inputs[node_name].size(-1), inputs[node_name].size(-1)),
IndexError: tensors used as indices must be long, byte or bool tensors
`

**Comment by Ceprin11** [comment]
@DarkLeaves I have the same problem,have you solved yet?

**Comment by DarkLeaves** [comment]
> [@DarkLeaves](https://github.com/DarkLeaves) I have the same problem,have you solved yet?

I forgot 
probably no

**Comment by Ceprin11** [comment]
> > [@DarkLeaves](https://github.com/DarkLeaves) I have the same problem,have you solved yet?
> 
> I forgot probably no

Thanks bro!I have solved it by using gitclone instead of directly downloading the zip file,which caused some missing files in timm.
